easy_admin:
    entities:
        BladeTemplate:
            class: App\Entity\BladeTemplate
            list:
                fields:
                    - name
                    - element
                    - gender
                    - battleRole
                    - weaponClass
                    - rarity
                    - { property: isMerc, type: 'boolean' }
                    - mercTeamName
                    - { property: canBeReleased, type: 'boolean' }
            form:
                fields:
                    - name
                    - gender
                    - battleRole
                    - weaponClass
                    - element
                    - rarity
                    - affinityTotal
                    - canBeReleased
                    - isMerc
                    - mercTeamName
        MercMissionPrerequisite:
            class: App\Entity\MercMissionPrerequisite
            list:
                fields:
                    - name
                    - sort
            form:
                fields:
                    - name
                    - sort
