twig:
    paths: ['%kernel.project_dir%/templates']
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes:
        - 'bootstrap_4_layout.html.twig'
        - '@EWZRecaptcha/Form/ewz_recaptcha_widget.html.twig'
        - 'form/_form.html.twig'
