stages:
  - build
  - stage
  - deploy
  - notify

variables:
  BUILD_NUMBER: ${CI_BUILD_REF_NAME}_${CI_BUILD_REF}
  APP_VERSION: ${CI_COMMIT_SHORT_SHA}
  IMAGE_BASENAME: ${CI_REGISTRY}/gamestuff.info/xeno2

build:
  stage: build
  image: docker:stable
  services:
    - docker:dind
  variables:
    COMPOSE_FILE: docker-compose.yaml
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: overlay2
  script:
    - apk add --no-cache gcc libc-dev libffi-dev make openssl-dev py-pip python2-dev
    - pip install docker-compose
    - docker info
    - docker login -u gitlab-ci-token -p ${CI_JOB_TOKEN} ${CI_REGISTRY}
    - docker-compose build
    - docker image tag ${IMAGE_BASENAME}/app:latest ${IMAGE_BASENAME}/app:${BUILD_NUMBER}
    - docker image tag ${IMAGE_BASENAME}/web:latest ${IMAGE_BASENAME}/web:${BUILD_NUMBER}
    - docker push ${IMAGE_BASENAME}/app:latest
    - docker push ${IMAGE_BASENAME}/app:${BUILD_NUMBER}
    - docker push ${IMAGE_BASENAME}/web:latest
    - docker push ${IMAGE_BASENAME}/web:${BUILD_NUMBER}

deploy:
  stage: deploy
  image: lwolf/kubectl_deployer
  environment:
    name: prod
    url: http://xeno2.gamestuff.info
  only:
    - master
  dependencies: []
  script:
    - /bin/sh deploy.sh ${CI_ENVIRONMENT_SLUG}
#
#sentry:
#  stage: notify
#  image: getsentry/sentry-cli
#  only:
#    - master
#  dependencies: []
#  script:
#    - sentry-cli releases new -p xeno2 ${BUILD_NUMBER}
#    - sentry-cli releases set-commits --auto ${BUILD_NUMBER}
#    - sentry-cli releases deploys ${BUILD_NUMBER} new -e prod
