stages:
  - build
  - stage
  - deploy

variables:
  DOCKER_COMPOSE_FILES: -f docker-compose.yml -f docker-compose.prod.yml -f docker-compose.gitlab.yml

build_assets:
  image: node
  stage: build
  cache:
    paths:
      - node_modules
  artifacts:
    paths:
      - app/public/dist
    expire_in: 1 day
  script:
    - cd app
    - yarn install
    - yarn run build

build_app:
  image: php:7.2-alpine
  stage: build
  cache:
    paths:
      - app/vendor
  artifacts:
    paths:
      - app/vendor
    expire_in: 1 day
  script:
    - apk update
    - apk add composer
    - cd app
    - composer install

build_images:
  image: docker:stable
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: overlay2
    CI_IMAGE_NAME: $CI_REGISTRY/gamestuff.info/xeno2
    CI_IMAGE_BRANCH_TAG:
  stage: stage
  script:
    - apk update
    - apk add --no-cache py-pip
    - pip install docker-compose
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker-compose $DOCKER_COMPOSE_FILES build
    - docker tag $CI_IMAGE_COMMIT_TAG $CI_IMAGE_BRANCH_TAG
    - docker-compose push
