image: php:7.1

cache:
  paths:
  - vendor/
  - node_modules/

before_script:
- apt-get update -yqq
- apt-get install -yqq apt-transport-https
- curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
- echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list
- curl -sL https://deb.nodesource.com/setup_8.x | bash -
- apt-get update -yqq
- apt-get install -yqq git yarn nodejs libmcrypt-dev libpq-dev libcurl4-gnutls-dev libicu-dev libvpx-dev libjpeg-dev libpng-dev libxpm-dev zlib1g-dev libfreetype6-dev libxml2-dev libexpat1-dev libbz2-dev libgmp3-dev libldap2-dev unixodbc-dev libsqlite3-dev libaspell-dev libsnmp-dev libpcre3-dev libtidy-dev
# Install PHP extensions
- docker-php-ext-install mbstring mcrypt curl json intl gd xml zip bz2 opcache
# Install & enable Xdebug for code coverage reports
- pecl install xdebug
- docker-php-ext-enable xdebug
# Install and run Composer
- curl -sS https://getcomposer.org/installer | php
- php composer.phar install
- yarn install

# Run our tests
test:
  variables:
    PHP_ARGS: '-d memory_limit=512M'
  script:
#  - php $PHP_ARGS -i
# Running the phpunit script without running tests ensures that the proper files
# are downloaded before testing.
  - bin/phpunit $PHP_ARGS --version
  - bin/phpunit $PHP_ARGS --configuration phpunit.xml.dist --coverage-text --colors=never
