stages:
  - build
  - stage
  - deploy

variables:
  IMAGE_NAME_PREFIX: gamestuff.info/xeno2
  DOCKER_COMPOSE_FILES: -f docker-compose.prod.yml -f docker-compose.gitlab.yml

before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

build_assets:
  image: node
  stage: build
  cache:
    paths:
      - node_modules
  artifacts:
    paths:
      - app/public/dist
    expire_in: 1 day
  script:
    - cd app
    - yarn install
    - yarn run build

build_app:
  image: php:7.2-alpine
  stage: build
  cache:
    paths:
      - app/vendor
  artifacts:
    paths:
      - app/vendor
    expire_in: 1 day
  script:
    - apk update
    - apk add composer
    - cd app
    - composer install

image_nginx:
  image: docker:stable
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: overlay2
    CI_IMAGE_NAME: $IMAGE_NAME_PREFIX/nginx
    CI_IMAGE_COMMIT_TAG: $CI_REGISTRY/$CI_IMAGE_NAME:$CI_COMMIT_SHA
    CI_IMAGE_BRANCH_TAG: $CI_REGISTRY/$CI_IMAGE_NAME:$CI_COMMIT_REF_SLUG
  stage: stage
  script:
    - docker-compose $DOCKER_COMPOSE_FILES build nginx
    - docker tag $CI_IMAGE_COMMIT_TAG $CI_IMAGE_BRANCH_TAG
    - docker-compose push nginx
