version:  '3.7'
services:
  mysql:
    image: mysql:5.7
    restart: on-failure
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_DATABASE
    ports:
      - '3306:3306'
  nginx:
    environment:
      NGINX_BACKEND_HOST: php
      NGINX_SERVER_ROOT: /var/www/html/public
      NGINX_VHOST_PRESET: php
    depends_on:
      - php
    volumes:
      - './app/public:/var/www/html/public:ro'
    ports:
      - '8000:80'
  php:
    environment:
      PHP_FPM_CLEAR_ENV: 'no'
      PHP_XDEBUG: '1'
      PHP_XDEBUG_DEFAULT_ENABLE: '1'
      PHP_XDEBUG_REMOTE_AUTOSTART: '1'
      PHP_XDEBUG_REMOTE_CONNECT_BACK: '1'
      APP_VERSION: ${APP_VERSION:-dev-local}
    depends_on:
      - mysql
      - mailhog
    volumes:
      - './app:/var/www/html:rw'
  mailhog:
    image: mailhog/mailhog:latest
    restart: on-failure
    ports:
      - '8025:8025'
