version:  '3.7'
services:
    mysql:
        image: mysql:5.7
        restart: on-failure
        environment:
            - MYSQL_ROOT_PASSWORD
            - MYSQL_USER
            - MYSQL_PASSWORD
            - MYSQL_DATABASE
    nginx:
        depends_on:
            - php
    php:
        volumes:
            - './app/var:/usr/src/app/var:rw'
        depends_on:
            - mysql
            - redis
            - mailhog
    mailhog:
        image: mailhog/mailhog:latest
        restart: on-failure
        ports:
            - '8025:8025'
