version: "3.7"

services:
  app:
    image: dragoonboots/xeno2/app
    build:
      context: .
      target: app
    environment:
      - APP_VERSION
      - BUILD_NUMBER
      - APP_ENV=prod
      - APP_SECRET
      - DATABASE_URL
      - MAILER_URL
      - RECAPTCHA_PUBLIC_KEY
      - RECAPTCHA_PRIVATE_KEY
      - GOOGLE_CLIENT_ID
      - GOOGLE_CLIENT_SECRET
      - SENTRY_DSN
    restart: always
    ports:
      - "80:80"
