version:  '3.7'
services:
    mysql:
        image: mysql:5.7
        restart: on-failure
        environment:
            - MYSQL_ROOT_PASSWORD
            - MYSQL_USER
            - MYSQL_PASSWORD
            - MYSQL_DATABASE
    nginx:
        build:
          context: .
          dockerfile: docker/nginx/Dockerfile
        restart: on-failure
        ports:
            - '80:80'
    php:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        restart: on-failure
        user: 1000:1000
    redis:
        image: redis:alpine
        restart: on-failure
