version:  '3.7'
services:
    nginx:
        restart: always
        depends_on:
            - php
    php:
        restart: always
        user: 1000:1000
        depends_on:
            - mysql
            - redis
    redis:
        image: redis:alpine
        restart: always
