version: "3.7"

services:
  edge:
    image: traefik:v2.4
    ports:
      # The HTTP port
      - "80:80"
      # HTTPS
      - "443:443"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
      - ./docker/traefik/static.yaml:/etc/traefik/traefik.yml
      - ./docker/traefik/dynamic.yaml:/etc/traefik/dynamic.yml
      - ./docker/traefik/certs:/etc/traefik/certs

  app:
    build:
      dockerfile: Dockerfile.dev
      target: app_dev
    env_file:
      - app/.env
    depends_on:
      - db
      - mail
    environment:
      APP_SECRET: 1
      APP_ENV: dev
      DATABASE_URL: 'postgres://xeno2:secret@db:5432/xeno2'
      MAILER_DSN: 'smtp://mail:1025'
      SENTRY_DSN: ''
      BUILD_NUMBER: debug
    volumes:
      - ./app:/var/www
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.xeno2-https.redirectscheme.scheme=https"
      - "traefik.http.routers.xeno2-http.rule=Host(`xeno2.localhost`)"
      - "traefik.http.routers.xeno2-http.entryPoints=web"
      - "traefik.http.routers.xeno2-http.middlewares=xeno2-https@docker"
      - "traefik.http.routers.xeno2-https.rule=Host(`xeno2.localhost`)"
      - "traefik.http.routers.xeno2-https.entryPoints=websecure"
      - "traefik.http.routers.xeno2-https.tls=true"

  db:
    image: postgres:12
    restart: always
    expose:
      - 5432
    ports:
      - 4321:5432
    environment:
      - POSTGRES_USER=xeno2
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=xeno2
    volumes:
      - /var/lib/postgresql/data

  mail:
    image: mailhog/mailhog
    expose:
      - 1025
    ports:
    - 8025:8025
