version:  '3.7'
services:
    mysql:
        image: mysql:5.7
        restart: on-failure
        environment:
            - MYSQL_ROOT_PASSWORD
            - MYSQL_USER
            - MYSQL_PASSWORD
            - MYSQL_DATABASE
    nginx:
        image: nginx:1.15.3-alpine
        restart: on-failure
        volumes:
            - './app/public/:/usr/src/app'
            - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
        ports:
            - '80:80'
        depends_on:
          - php
    php:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        restart: on-failure
        env_file:
            - .env
        user: 1000:1000
        volumes:
          - './app/var:/usr/src/app/var:rw'
        depends_on:
            - mysql
            - redis
            - mailhog
    redis:
        image: redis:alpine
        restart: on-failure

    mailhog:
        image: mailhog/mailhog:latest
        restart: on-failure
        ports:
            - '8025:8025'
