version: "3.7"

services:
  app:
    image: "${IMAGE_BASENAME}/app:${BUILD_NUMBER}"
    environment:
      - APP_VERSION
      - BUILD_NUMBER
      - APP_ENV=prod
      - APP_SECRET
      - DATABASE_URL
      - MAILER_URL
      - RECAPTCHA_PUBLIC_KEY
      - RECAPTCHA_PRIVATE_KEY
      - GOOGLE_CLIENT_ID
      - GOOGLE_CLIENT_SECRET
      - SENTRY_DSN
    restart: always

  web:
    image: "${IMAGE_BASENAME}/web:${BUILD_NUMBER}"
    environment:
      - NGINX_BACKEND_HOST=app
    restart: always
    ports:
      - "80:80"
