kind: Deployment
apiVersion: apps/v1
metadata:
  name: traefik
  labels:
    app: traefik
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traefik
  template:
    metadata:
      labels:
        app: traefik
    spec:
      terminationGracePeriodSeconds: 60
      containers:
        - image: traefik
          name: traefik
          args:
            - --configFile=/mnt/traefik-config/traefik.toml
          ports:
            - name: http
              containerPort: 80
            - name: https
              containerPort: 443
          volumeMounts:
            - mountPath: /mnt/traefik-config
              name: traefik-config
            - mountPath: /mnt/tls
              name: traefik-tls
      volumes:
        - name: traefik-config
          configMap:
            name: traefik-config
        - name: traefik-tls
          secret:
            secretName: xeno2-gamestuff-info-tls
---
kind: Service
apiVersion: v1
metadata:
  name: traefik-service
spec:
  selector:
    app: traefik
  ports:
    - protocol: TCP
      port: 80
      name: http
    - protocol: TCP
      port: 443
      name: https
  type: LoadBalancer
