CREATE TABLE blade_affinity_node
(
    id INTEGER PRIMARY KEY NOT NULL,
    blade_id INTEGER DEFAULT NULL,
    affinity_node_id INTEGER DEFAULT NULL,
    level INTEGER NOT NULL,
    max_level INTEGER NOT NULL,
    CONSTRAINT FK_D7F9A2908118485F FOREIGN KEY (blade_id) REFERENCES blade_superclass (id),
    CONSTRAINT FK_D7F9A290F810347F FOREIGN KEY (affinity_node_id) REFERENCES affinity_node (id)
);
CREATE INDEX IDX_D7F9A2908118485F ON blade_affinity_node (blade_id);
CREATE INDEX IDX_D7F9A290F810347F ON blade_affinity_node (affinity_node_id);
INSERT INTO blade_affinity_node (id, blade_id, affinity_node_id, level, max_level) VALUES (1, 1, 4, 0, 3);
INSERT INTO blade_affinity_node (id, blade_id, affinity_node_id, level, max_level) VALUES (2, 1, 17, 0, 3);
INSERT INTO blade_affinity_node (id, blade_id, affinity_node_id, level, max_level) VALUES (3, 1, 30, 0, 3);
INSERT INTO blade_affinity_node (id, blade_id, affinity_node_id, level, max_level) VALUES (4, 2, 5, 0, 3);
INSERT INTO blade_affinity_node (id, blade_id, affinity_node_id, level, max_level) VALUES (5, 2, 17, 0, 3);
INSERT INTO blade_affinity_node (id, blade_id, affinity_node_id, level, max_level) VALUES (6, 2, 19, 0, 3);
INSERT INTO blade_affinity_node (id, blade_id, affinity_node_id, level, max_level) VALUES (7, 3, 7, 0, 3);
INSERT INTO blade_affinity_node (id, blade_id, affinity_node_id, level, max_level) VALUES (8, 3, 10, 0, 3);
INSERT INTO blade_affinity_node (id, blade_id, affinity_node_id, level, max_level) VALUES (9, 4, 21, 0, 3);
INSERT INTO blade_affinity_node (id, blade_id, affinity_node_id, level, max_level) VALUES (10, 4, 23, 0, 3);
INSERT INTO blade_affinity_node (id, blade_id, affinity_node_id, level, max_level) VALUES (11, 4, 24, 0, 3);
INSERT INTO blade_affinity_node (id, blade_id, affinity_node_id, level, max_level) VALUES (12, 5, 22, 0, 3);
INSERT INTO blade_affinity_node (id, blade_id, affinity_node_id, level, max_level) VALUES (13, 5, 18, 0, 3);
INSERT INTO blade_affinity_node (id, blade_id, affinity_node_id, level, max_level) VALUES (14, 5, 9, 0, 3);
INSERT INTO blade_affinity_node (id, blade_id, affinity_node_id, level, max_level) VALUES (15, 6, 20, 0, 3);
INSERT INTO blade_affinity_node (id, blade_id, affinity_node_id, level, max_level) VALUES (16, 6, 16, 0, 3);
INSERT INTO blade_affinity_node (id, blade_id, affinity_node_id, level, max_level) VALUES (17, 6, 12, 0, 3);
INSERT INTO blade_affinity_node (id, blade_id, affinity_node_id, level, max_level) VALUES (18, 7, 3, 0, 3);
INSERT INTO blade_affinity_node (id, blade_id, affinity_node_id, level, max_level) VALUES (19, 7, 22, 0, 3);
INSERT INTO blade_affinity_node (id, blade_id, affinity_node_id, level, max_level) VALUES (20, 7, 13, 0, 3);
INSERT INTO blade_affinity_node (id, blade_id, affinity_node_id, level, max_level) VALUES (21, 8, 8, 0, 3);
INSERT INTO blade_affinity_node (id, blade_id, affinity_node_id, level, max_level) VALUES (22, 8, 34, 0, 1);
INSERT INTO blade_affinity_node (id, blade_id, affinity_node_id, level, max_level) VALUES (23, 8, 22, 0, 3);
INSERT INTO blade_affinity_node (id, blade_id, affinity_node_id, level, max_level) VALUES (24, 9, 4, 0, 3);
INSERT INTO blade_affinity_node (id, blade_id, affinity_node_id, level, max_level) VALUES (25, 9, 20, 0, 3);
INSERT INTO blade_affinity_node (id, blade_id, affinity_node_id, level, max_level) VALUES (26, 9, 14, 0, 3);
INSERT INTO blade_affinity_node (id, blade_id, affinity_node_id, level, max_level) VALUES (27, 10, 7, 0, 3);
INSERT INTO blade_affinity_node (id, blade_id, affinity_node_id, level, max_level) VALUES (28, 10, 16, 0, 3);
INSERT INTO blade_affinity_node (id, blade_id, affinity_node_id, level, max_level) VALUES (29, 10, 21, 0, 3);
INSERT INTO blade_affinity_node (id, blade_id, affinity_node_id, level, max_level) VALUES (30, 11, 11, 0, 3);
INSERT INTO blade_affinity_node (id, blade_id, affinity_node_id, level, max_level) VALUES (31, 11, 21, 0, 3);
INSERT INTO blade_affinity_node (id, blade_id, affinity_node_id, level, max_level) VALUES (32, 11, 47, 0, 3);
INSERT INTO blade_affinity_node (id, blade_id, affinity_node_id, level, max_level) VALUES (33, 12, 1, 0, 3);
INSERT INTO blade_affinity_node (id, blade_id, affinity_node_id, level, max_level) VALUES (34, 12, 21, 0, 3);
INSERT INTO blade_affinity_node (id, blade_id, affinity_node_id, level, max_level) VALUES (35, 12, 38, 0, 3);
INSERT INTO blade_affinity_node (id, blade_id, affinity_node_id, level, max_level) VALUES (36, 13, 10, 0, 5);
INSERT INTO blade_affinity_node (id, blade_id, affinity_node_id, level, max_level) VALUES (37, 13, 2, 0, 3);
INSERT INTO blade_affinity_node (id, blade_id, affinity_node_id, level, max_level) VALUES (38, 13, 48, 0, 5);
INSERT INTO blade_affinity_node (id, blade_id, affinity_node_id, level, max_level) VALUES (39, 14, 50, 0, 5);
INSERT INTO blade_affinity_node (id, blade_id, affinity_node_id, level, max_level) VALUES (40, 14, 23, 0, 1);
INSERT INTO blade_affinity_node (id, blade_id, affinity_node_id, level, max_level) VALUES (41, 14, 16, 0, 1);
INSERT INTO blade_affinity_node (id, blade_id, affinity_node_id, level, max_level) VALUES (42, 14, 14, 0, 1);
INSERT INTO blade_affinity_node (id, blade_id, affinity_node_id, level, max_level) VALUES (43, 15, 1, 0, 3);
INSERT INTO blade_affinity_node (id, blade_id, affinity_node_id, level, max_level) VALUES (44, 15, 10, 0, 3);
INSERT INTO blade_affinity_node (id, blade_id, affinity_node_id, level, max_level) VALUES (45, 15, 51, 0, 3);
INSERT INTO blade_affinity_node (id, blade_id, affinity_node_id, level, max_level) VALUES (46, 16, 2, 0, 3);
INSERT INTO blade_affinity_node (id, blade_id, affinity_node_id, level, max_level) VALUES (47, 16, 13, 0, 3);
INSERT INTO blade_affinity_node (id, blade_id, affinity_node_id, level, max_level) VALUES (48, 16, 44, 0, 3);
INSERT INTO blade_affinity_node (id, blade_id, affinity_node_id, level, max_level) VALUES (49, 17, 3, 0, 5);
INSERT INTO blade_affinity_node (id, blade_id, affinity_node_id, level, max_level) VALUES (50, 17, 17, 0, 3);
INSERT INTO blade_affinity_node (id, blade_id, affinity_node_id, level, max_level) VALUES (51, 17, 46, 0, 5);
INSERT INTO blade_affinity_node (id, blade_id, affinity_node_id, level, max_level) VALUES (52, 18, 6, 0, 3);
INSERT INTO blade_affinity_node (id, blade_id, affinity_node_id, level, max_level) VALUES (53, 18, 16, 0, 3);
INSERT INTO blade_affinity_node (id, blade_id, affinity_node_id, level, max_level) VALUES (54, 18, 42, 0, 3);
INSERT INTO blade_affinity_node (id, blade_id, affinity_node_id, level, max_level) VALUES (55, 19, 8, 0, 3);
INSERT INTO blade_affinity_node (id, blade_id, affinity_node_id, level, max_level) VALUES (56, 19, 20, 0, 3);
INSERT INTO blade_affinity_node (id, blade_id, affinity_node_id, level, max_level) VALUES (57, 19, 45, 0, 5);
INSERT INTO blade_affinity_node (id, blade_id, affinity_node_id, level, max_level) VALUES (58, 20, 24, 0, 3);
INSERT INTO blade_affinity_node (id, blade_id, affinity_node_id, level, max_level) VALUES (59, 20, 15, 0, 3);
INSERT INTO blade_affinity_node (id, blade_id, affinity_node_id, level, max_level) VALUES (60, 20, 52, 0, 3);
INSERT INTO blade_affinity_node (id, blade_id, affinity_node_id, level, max_level) VALUES (61, 21, 20, 0, 3);
INSERT INTO blade_affinity_node (id, blade_id, affinity_node_id, level, max_level) VALUES (62, 21, 18, 0, 3);
INSERT INTO blade_affinity_node (id, blade_id, affinity_node_id, level, max_level) VALUES (63, 21, 32, 0, 3);
INSERT INTO blade_affinity_node (id, blade_id, affinity_node_id, level, max_level) VALUES (64, 22, 19, 0, 5);
INSERT INTO blade_affinity_node (id, blade_id, affinity_node_id, level, max_level) VALUES (65, 22, 3, 0, 3);
INSERT INTO blade_affinity_node (id, blade_id, affinity_node_id, level, max_level) VALUES (66, 22, 22, 0, 3);
INSERT INTO blade_affinity_node (id, blade_id, affinity_node_id, level, max_level) VALUES (67, 23, 12, 0, 3);
INSERT INTO blade_affinity_node (id, blade_id, affinity_node_id, level, max_level) VALUES (68, 23, 18, 0, 3);
INSERT INTO blade_affinity_node (id, blade_id, affinity_node_id, level, max_level) VALUES (69, 23, 33, 0, 5);
INSERT INTO blade_affinity_node (id, blade_id, affinity_node_id, level, max_level) VALUES (70, 24, 23, 0, 3);
INSERT INTO blade_affinity_node (id, blade_id, affinity_node_id, level, max_level) VALUES (71, 24, 15, 0, 3);
INSERT INTO blade_affinity_node (id, blade_id, affinity_node_id, level, max_level) VALUES (72, 24, 40, 0, 3);
INSERT INTO blade_affinity_node (id, blade_id, affinity_node_id, level, max_level) VALUES (73, 25, 1, 0, 3);
INSERT INTO blade_affinity_node (id, blade_id, affinity_node_id, level, max_level) VALUES (74, 25, 31, 0, 3);
INSERT INTO blade_affinity_node (id, blade_id, affinity_node_id, level, max_level) VALUES (75, 25, 19, 0, 3);
INSERT INTO blade_affinity_node (id, blade_id, affinity_node_id, level, max_level) VALUES (76, 26, 24, 0, 5);
INSERT INTO blade_affinity_node (id, blade_id, affinity_node_id, level, max_level) VALUES (77, 26, 2, 0, 5);
INSERT INTO blade_affinity_node (id, blade_id, affinity_node_id, level, max_level) VALUES (78, 26, 17, 0, 5);
INSERT INTO blade_affinity_node (id, blade_id, affinity_node_id, level, max_level) VALUES (79, 27, 3, 0, 3);
INSERT INTO blade_affinity_node (id, blade_id, affinity_node_id, level, max_level) VALUES (80, 27, 24, 0, 3);
INSERT INTO blade_affinity_node (id, blade_id, affinity_node_id, level, max_level) VALUES (81, 27, 49, 0, 5);
INSERT INTO blade_affinity_node (id, blade_id, affinity_node_id, level, max_level) VALUES (82, 28, 35, 0, 3);
INSERT INTO blade_affinity_node (id, blade_id, affinity_node_id, level, max_level) VALUES (83, 28, 36, 0, 3);
INSERT INTO blade_affinity_node (id, blade_id, affinity_node_id, level, max_level) VALUES (84, 28, 37, 0, 3);
INSERT INTO blade_affinity_node (id, blade_id, affinity_node_id, level, max_level) VALUES (85, 29, 8, 0, 5);
INSERT INTO blade_affinity_node (id, blade_id, affinity_node_id, level, max_level) VALUES (86, 29, 24, 0, 5);
INSERT INTO blade_affinity_node (id, blade_id, affinity_node_id, level, max_level) VALUES (87, 29, 21, 0, 5);
INSERT INTO blade_affinity_node (id, blade_id, affinity_node_id, level, max_level) VALUES (88, 30, 19, 0, 3);
INSERT INTO blade_affinity_node (id, blade_id, affinity_node_id, level, max_level) VALUES (89, 30, 7, 0, 3);
INSERT INTO blade_affinity_node (id, blade_id, affinity_node_id, level, max_level) VALUES (90, 30, 15, 0, 3);
INSERT INTO blade_affinity_node (id, blade_id, affinity_node_id, level, max_level) VALUES (91, 31, 6, 0, 3);
INSERT INTO blade_affinity_node (id, blade_id, affinity_node_id, level, max_level) VALUES (92, 31, 17, 0, 3);
INSERT INTO blade_affinity_node (id, blade_id, affinity_node_id, level, max_level) VALUES (93, 31, 23, 0, 3);
INSERT INTO blade_affinity_node (id, blade_id, affinity_node_id, level, max_level) VALUES (94, 32, 19, 0, 3);
INSERT INTO blade_affinity_node (id, blade_id, affinity_node_id, level, max_level) VALUES (95, 32, 22, 0, 3);
INSERT INTO blade_affinity_node (id, blade_id, affinity_node_id, level, max_level) VALUES (96, 32, 53, 0, 3);
INSERT INTO blade_affinity_node (id, blade_id, affinity_node_id, level, max_level) VALUES (97, 33, 39, 0, 3);
INSERT INTO blade_affinity_node (id, blade_id, affinity_node_id, level, max_level) VALUES (98, 33, 14, 0, 3);
INSERT INTO blade_affinity_node (id, blade_id, affinity_node_id, level, max_level) VALUES (99, 33, 20, 0, 3);
INSERT INTO blade_affinity_node (id, blade_id, affinity_node_id, level, max_level) VALUES (100, 34, 23, 0, 3);
INSERT INTO blade_affinity_node (id, blade_id, affinity_node_id, level, max_level) VALUES (101, 34, 9, 0, 3);
INSERT INTO blade_affinity_node (id, blade_id, affinity_node_id, level, max_level) VALUES (102, 34, 41, 0, 3);
INSERT INTO blade_affinity_node (id, blade_id, affinity_node_id, level, max_level) VALUES (103, 35, 12, 0, 3);
INSERT INTO blade_affinity_node (id, blade_id, affinity_node_id, level, max_level) VALUES (104, 35, 6, 0, 3);
INSERT INTO blade_affinity_node (id, blade_id, affinity_node_id, level, max_level) VALUES (105, 35, 54, 0, 3);
INSERT INTO blade_affinity_node (id, blade_id, affinity_node_id, level, max_level) VALUES (106, 36, 43, 0, 5);
INSERT INTO blade_affinity_node (id, blade_id, affinity_node_id, level, max_level) VALUES (107, 36, 13, 0, 3);
INSERT INTO blade_affinity_node (id, blade_id, affinity_node_id, level, max_level) VALUES (108, 36, 18, 0, 3);
INSERT INTO blade_affinity_node (id, blade_id, affinity_node_id, level, max_level) VALUES (109, 37, 5, 0, 3);
INSERT INTO blade_affinity_node (id, blade_id, affinity_node_id, level, max_level) VALUES (110, 37, 22, 0, 3);
INSERT INTO blade_affinity_node (id, blade_id, affinity_node_id, level, max_level) VALUES (111, 37, 55, 0, 3);
INSERT INTO blade_affinity_node (id, blade_id, affinity_node_id, level, max_level) VALUES (112, 38, 7, 0, 3);
INSERT INTO blade_affinity_node (id, blade_id, affinity_node_id, level, max_level) VALUES (113, 38, 12, 0, 3);
INSERT INTO blade_affinity_node (id, blade_id, affinity_node_id, level, max_level) VALUES (114, 38, 18, 0, 3);