CREATE TABLE merc_mission
(
    id INTEGER PRIMARY KEY NOT NULL,
    nation_id INTEGER DEFAULT NULL,
    duration TIME NOT NULL,
    repeatable BOOLEAN NOT NULL,
    name VARCHAR(255) NOT NULL,
    slug VARCHAR(255) NOT NULL
);
CREATE UNIQUE INDEX UNIQ_FAF4B51F989D9B62 ON merc_mission (slug);
CREATE INDEX IDX_FAF4B51FAE3899 ON merc_mission (nation_id);