sentry:
    dsn: '%env(SENTRY_DSN)%'
    options:
        curl_method: async
        error_types: E_ALL & ~E_DEPRECATED & ~E_NOTICE
        environment: "%kernel.environment%"

    skip_capture:  # To skip certain exceptions, specify a list below
        - 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException'
        - 'Symfony\Component\HttpKernel\Exception\BadRequestHttpException'
        - 'Symfony\Component\HttpKernel\Exception\AccessDeniedHttpException'
