apiVersion: batch/v1
kind: Job
metadata:
  name: db-migrations
spec:
  template:
    metadata:
      name: db-migrations
    spec:
      imagePullSecrets:
        - name: gitlab-registry
      containers:
        - env:
            - name: PHP_XDEBUG
              value: "0"
            - name: PHP_XDEBUG_DEFAULT_ENABLE
              value: "0"
            - name: PHP_FPM_CLEAR_ENV
              value: 'no'
            - name: APP_ENV
              value: prod
            - name: APP_DEBUG
              value: "1"
            - name: APP_SECRET
              valueFrom:
                secretKeyRef:
                  name: xeno2-secret
                  key: app.secret
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: xeno2-secret
                  key: database.url
            - name: MAILER_URL
              valueFrom:
                configMapKeyRef:
                  name: xeno2
                  key: mailer.url
            - name: RECAPTCHA_PUBLIC_KEY
              valueFrom:
                secretKeyRef:
                  name: xeno2-secret
                  key: recaptcha.public_key
            - name: RECAPTCHA_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: xeno2-secret
                  key: recaptcha.private_key
            - name: GOOGLE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: xeno2-secret
                  key: google.client_id
            - name: GOOGLE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: xeno2-secret
                  key: google.client_secret
            - name: SENTRY_DSN
              valueFrom:
                secretKeyRef:
                  name: xeno2-secret
                  key: sentry.dsn
          name: db-migrations
          image: ${IMAGE_BASENAME}/php:${BUILD_NUMBER}
          command: ['bash']
          args: ['/var/www/html/bin/db-migrations.sh' ]
        - name: cloudsql-proxy
          image: gcr.io/cloudsql-docker/gce-proxy:1.11
          command: ["/cloud_sql_proxy",
                    "-instances=${CLOUDSQL_INSTANCE}=tcp:3306",
                    "-credential_file=/secrets/cloudsql/credentials.json"]
          securityContext:
            runAsUser: 2  # non-root user
            allowPrivilegeEscalation: false
          volumeMounts:
            - name: secret-xeno2-cloudsql
              mountPath: /secrets/cloudsql
              readOnly: true
      volumes:
        - name: secret-xeno2-cloudsql
          secret:
            secretName: xeno2-cloudsql
      restartPolicy: Never
