parameters:
    # Testing-only keys are the default
    env(RECAPTCHA_PUBLIC_KEY): 6LeIxAcTAAAAAJcZVRqyHh71UMIEGNQ_MXjiZKhI
    env(RECAPTCHA_PRIVATE_KEY): 6LeIxAcTAAAAAGG-vFI1TnRWxMZNFuojJ4WifJWe
    templating.engines: [ 'none' ]

ewz_recaptcha:
    public_key:  '%env(RECAPTCHA_PUBLIC_KEY)%'
    private_key: '%env(RECAPTCHA_PRIVATE_KEY)%'
