providers:
  docker:
    defaultRule: "Host(`{{ trimPrefix `/` .Name }}.docker.localhost`)"
    exposedbydefault: false
  file:
    filename: /etc/traefik/dynamic.yml
    watch: true

api:
  insecure: true

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"
